package parser

import (
	"bufio"
	"fmt"
	"os"
	"strings"
)

// generateMakeheadersFile generates a file compatible with the makeheaders utility
func (p *Parser) generateMakeheadersFile() error {
	// Create the makeheaders file path by replacing the .h extension with .gh
	mhFilename := strings.TrimSuffix(p.HeaderFilename, ".h") + ".gh"
	
	// Open the makeheaders file for writing
	mhFile, err := os.Create(mhFilename)
	if err != nil {
		return fmt.Errorf("cannot create makeheaders file: %v", err)
	}
	defer mhFile.Close()
	
	// Use a buffered writer for better performance
	writer := bufio.NewWriter(mhFile)
	
	// Write the file header
	header := "/* This file was automatically generated by Lemon from input grammar\n"
	header += fmt.Sprintf("** source file \"%s\".\n", p.Grammar)
	header += fmt.Sprintf("** Generator version: %s\n*/\n\n", Version)
	writer.WriteString(header)
	
	// Write token definitions
	writer.WriteString("/* Token definitions */\n")
	for _, sym := range p.Symbols {
		if sym.IsTerminal {
			prefix := p.TokenPrefix
			writer.WriteString(fmt.Sprintf("#define %s%-30s %d\n", prefix, sym.Name, sym.Index))
		}
	}
	writer.WriteString("\n")
	
	// Write parser API declarations
	writer.WriteString(fmt.Sprintf("/* %s API definitions */\n", p.Name))
	writer.WriteString(fmt.Sprintf("void *%sAlloc(void *(*mallocProc)(size_t));\n", p.Name))
	writer.WriteString(fmt.Sprintf("void %sFree(void *parser, void (*freeProc)(void*));\n", p.Name))
	writer.WriteString(fmt.Sprintf("void %sTrace(FILE *stream, char *zPrefix);\n", p.Name))
	
	// Parse function
	apiStr := fmt.Sprintf("void %sParse(void *parser, int tokenCode, %s tokenValue, void *arg);\n",
		p.Name, p.TokenType)
	writer.WriteString(apiStr)
	
	// Add any extra arguments if specified
	if p.ExtraArgument != "" {
		writer.WriteString(fmt.Sprintf("/* Extra argument: %s */\n", p.ExtraArgument))
	}
	
	// Flush the writer to ensure all data is written to the file
	return writer.Flush()
}

// generateSQLFile generates an SQLite database file with parser information
func (p *Parser) generateSQLFile() error {
	// Create the SQL file path by replacing the .c extension with .sql
	sqlFilename := strings.TrimSuffix(p.OutputFilename, ".c") + ".sql"
	
	// Open the SQL file for writing
	sqlFile, err := os.Create(sqlFilename)
	if err != nil {
		return fmt.Errorf("cannot create SQL file: %v", err)
	}
	defer sqlFile.Close()
	
	// Use a buffered writer for better performance
	writer := bufio.NewWriter(sqlFile)
	
	// Write the initial transaction and schema
	writer.WriteString("BEGIN;\n")
	writer.WriteString("CREATE TABLE symbol(\n")
	writer.WriteString("  id INTEGER PRIMARY KEY,\n")
	writer.WriteString("  name TEXT NOT NULL,\n")
	writer.WriteString("  isTerminal BOOLEAN NOT NULL,\n")
	writer.WriteString("  fallback INTEGER REFERENCES symbol")
	writer.WriteString(" DEFERRABLE INITIALLY DEFERRED\n")
	writer.WriteString(");\n")
	
	// Insert symbol data
	for _, sym := range p.Symbols {
		sqlInsert := fmt.Sprintf(
			"INSERT INTO symbol(id,name,isTerminal,fallback)VALUES(%d,'%s',%s",
			sym.Index, sym.Name,
			fmt.Sprintf("%t", sym.IsTerminal),
		)
		
		if sym.Fallback != nil {
			sqlInsert += fmt.Sprintf(",%d);\n", sym.Fallback.Index)
		} else {
			sqlInsert += ",NULL);\n"
		}
		writer.WriteString(sqlInsert)
	}
	
	// Create tables for rules and rule RHS
	writer.WriteString("CREATE TABLE rule(\n")
	writer.WriteString("  ruleid INTEGER PRIMARY KEY,\n")
	writer.WriteString("  lhs INTEGER REFERENCES symbol(id),\n")
	writer.WriteString("  txt TEXT\n")
	writer.WriteString(");\n")
	
	writer.WriteString("CREATE TABLE rulerhs(\n")
	writer.WriteString("  ruleid INTEGER REFERENCES rule(ruleid),\n")
	writer.WriteString("  pos INTEGER,\n")
	writer.WriteString("  sym INTEGER REFERENCES symbol(id)\n")
	writer.WriteString(");\n")
	
	// Insert rule data
	for _, rule := range p.Rule {
		// Insert the rule
		ruleInsert := fmt.Sprintf(
			"INSERT INTO rule(ruleid,lhs,txt)VALUES(%d,%d,'",
			rule.RuleNum, rule.Lhs.Index,
		)
		writer.WriteString(ruleInsert)
		
		// Write the rule text
		ruleText := fmt.Sprintf("%s ::=", rule.Lhs.Name)
		for _, sym := range rule.Rhs {
			ruleText += fmt.Sprintf(" %s", sym.Name)
		}
		ruleText += "');\n"
		writer.WriteString(ruleText)
		
		// Insert each RHS symbol
		for i, sym := range rule.Rhs {
			rhsInsert := fmt.Sprintf(
				"INSERT INTO rulerhs(ruleid,pos,sym)VALUES(%d,%d,%d);\n",
				rule.RuleNum, i, sym.Index,
			)
			writer.WriteString(rhsInsert)
		}
	}
	
	// Commit the transaction
	writer.WriteString("COMMIT;\n")
	
	// Flush the writer to ensure all data is written to the file
	return writer.Flush()
}